version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo npm install -g npm@latest

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}

      - run: sudo npm install -g greenkeeper-lockfile@1
      - run: npm install
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: greenkeeper-lockfile-update
      - run: ./cc-test-reporter before-build
      - run: npm test
      - run: npm run build
      - run: ./cc-test-reporter after-build -t lcov --exit-code $?
      - run: greenkeeper-lockfile-upload
